version: "3.7"

services:
  gungnir:
    # build: .
    image: ghcr.io/geekmasher/gungnir:main
    container_name: "gungnir"
    environment:
      # move this to a more secure place
      DEPENDENCYTRACK_TOKEN: HereBeMyToken
      DEPENDENCYTRACK_URL: https://api.dependencytrack
    # env_file:
      # [optional] pass in to the container the os-release info
      # - /etc/os-release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

