name: Semgrep

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/ci 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      - run: semgrep . --sarif --output semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          # more at semgrep.dev/explore
          SEMGREP_RULES: p/default

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
